"""The verified ledger.

Every line here was generated from an engine verdict. The model never writes to it. That is
the whole point: a model that claims it hit cannot enter that claim as fact, because the only
thing that reaches this block is what the engine decided.

Old lines are **compacted**, not truncated. Rolling truncation would silently delete evidence
that a plan already failed, which is exactly the evidence that stops the model retrying it.
Compaction keeps every outcome as a count, and keeps the reasons the engine gave.
"""

from __future__ import annotations

from collections import Counter

from ..models import LedgerDigest, LedgerEntry

#: How many lines stay verbatim. Everything older is folded into the digest.
DEFAULT_KEEP_RECENT = 12
#: The digest names the most common rejection reasons; the rest become "other".
DIGEST_REASON_LIMIT = 5


def compact(
    entries: list[LedgerEntry],
    digest: LedgerDigest | None,
    *,
    keep_recent: int = DEFAULT_KEEP_RECENT,
) -> tuple[list[LedgerEntry], LedgerDigest | None]:
    """Fold everything older than `keep_recent` into the digest.

    The digest is bounded by construction -- counts, not lines -- so a session of any length
    keeps its full outcome history in a fixed number of tokens.
    """
    keep_recent = max(0, keep_recent)
    if len(entries) <= keep_recent:
        return list(entries), digest

    overflow = entries[: len(entries) - keep_recent]
    kept = entries[len(entries) - keep_recent :]
    return kept, _fold(overflow, digest)


def _fold(entries: list[LedgerEntry], digest: LedgerDigest | None) -> LedgerDigest:
    applied = Counter(digest.applied if digest else {})
    rejected = Counter(digest.rejected if digest else {})
    reasons = Counter(digest.reasons if digest else {})

    for entry in entries:
        if entry.ok:
            applied[entry.tool] += 1
        else:
            rejected[entry.tool] += 1
            if entry.reason:
                reasons[entry.reason] += 1

    turns = [entry.turn for entry in entries]
    return LedgerDigest(
        from_turn=min(digest.from_turn, *turns) if digest else min(turns),
        to_turn=max(digest.to_turn, *turns) if digest else max(turns),
        total=(digest.total if digest else 0) + len(entries),
        applied=dict(applied.most_common()),
        rejected=dict(rejected.most_common()),
        reasons=_cap_reasons(reasons),
    )


def _cap_reasons(reasons: Counter[str]) -> dict[str, int]:
    """Keep the commonest reasons verbatim and roll the tail into one line.

    Still compaction: the count of rejections never changes, only how finely the reasons are
    named.
    """
    if len(reasons) <= DIGEST_REASON_LIMIT:
        return dict(reasons.most_common())
    top = reasons.most_common(DIGEST_REASON_LIMIT)
    tail = sum(count for _, count in reasons.most_common()[DIGEST_REASON_LIMIT:])
    return {**dict(top), f"other reasons ({len(reasons) - DIGEST_REASON_LIMIT} kinds)": tail}


def render(entries: list[LedgerEntry], digest: LedgerDigest | None) -> str:
    """Render the block. Empty string when there is nothing yet, so the section is dropped."""
    if not entries and digest is None:
        return ""

    lines = [
        "## Verified ledger",
        "Generated by the engine from its own verdicts, not from anything written above. If a "
        "line says a call was rejected, it was rejected, whatever else in this prompt implies.",
    ]

    if digest is not None:
        lines.append(
            f"Turns {digest.from_turn}–{digest.to_turn}, compacted "
            f"({digest.total} mutation{'s' if digest.total != 1 else ''} attempted):"
        )
        if digest.applied:
            lines.append("  applied: " + _counts(digest.applied))
        if digest.rejected:
            lines.append("  rejected: " + _counts(digest.rejected))
        if digest.reasons:
            lines.append(
                "  reasons the engine gave: "
                + ", ".join(f'"{reason}" ×{count}' for reason, count in digest.reasons.items())
            )

    for entry in entries:
        reason = f" — {entry.reason}" if entry.reason else ""
        lines.append(f"  t{entry.turn} {entry.intent} -> {entry.outcome}{reason}")
    return "\n".join(lines)


def _counts(counts: dict[str, int]) -> str:
    return ", ".join(f"{tool} ×{count}" for tool, count in counts.items())
